name: FoliaPerms
version: '${version}'
main: kaiakk.foliaPerms.FoliaPerms
api-version: '26.1'
authors: [
  KaiakK,
  MoRanYue
]
description: A fork of simple Folia-only permission manager with container UI editor, group inheritance, and advanced permission handling.
website: https://github.com/MoRanYue/FoliaPermsFork
folia-supported: true
load: STARTUP

commands:
  fperm:
    description: "Manage FoliaPerms (groups/users/permissions)"
    usage: "/fperm <help|reload|gather|refresh|user|group|check|listperms>"
    permission: folia.perms
    permission-message: "You don't have permission to use this command."

permissions:
  folia.perms:
    description: "Allow use of FoliaPerms admin commands"
    default: op # given by default to server operators, so that there wouldn't be a lockout situation